### ISSUE TITLE
¿Where are the demos of PHP and Apache Cordova?

### ISSUE THREAD

**Issue by PeterConchaR** [Azure-Readiness/DevCamp#3]
Hi all,

In the reposositorio of "Demo Geolocation PHP Service" (https://github.com/Azure-Readiness/Demo-Geolocation-PHP-Service) says that it is in the repository MicrosoftAzureTrainingKit; but there tell us that been replaced with this, and aren't the demos PHP and Apache Cordova. The alternative to individually download packages, has the broken link. (Microsoft Azure Training Kit WebPI Packages - http://composer-test.azurewebsites.net/).

You can someone help me with those demos :)

**Comment by SidneyAndrewsOpsgility** [comment]
When I look at the new demo it's to create a PHP site and host it in Azure Websites (https://github.com/Azure-Readiness/MicrosoftAzureTrainingKit/blob/master/Demos/Demo-Geolocation-PHP-Service/Demo.md).  Is this not the demo you are looking for?  I apologize if I don't understand.

**Comment by pkefal** [comment]
Unfortunately, that's only the script of the demo. At some points it refers to the /source/ folder which contains the source of the PHP website etc. and that is what is actually missing.

**Comment by SidneyAndrewsOpsgility** [comment]
I got confused about the source directory :-).  I pulled down the Web PI package and it didn't include the source folder either.  This was a mess to find but you can look at the history of the readme to see that there is a source folder here:

https://github.com/Azure-Samples/Geolocation-PHP-Service

Is that what you are looking for?

It looks like the link to download the source code was removed.  You can see the link in this revision:

https://github.com/Azure-Readiness/Demo-Geolocation-PHP-Service/commit/7ac7e053fd7e8885216a13049b118cd9cab3cafd#diff-04c6e90faac2675aa89e2176d2eec7d8

If this is what you need, let us know and we should probably file an issue in that repo instead of this repo.

**Comment by pkefal** [comment]
Yes, that's indeed the one.

**Comment by jongalloway** [comment]
These demos have been removed from the DevCamp. Closing this issue.
